networks:
  default:
    name: purepyodbc

x-common-setup: &common-setup
  volumes:
    - .:/usr/src/app
  depends_on:
    - mysql
    - postgresql
    - sqlserver
  environment:
    # These are used in conftest.py so that tests target the
    # db services defined in this file.
    MYSQL_HOST: mysql
    POSTGRESQL_HOST: postgresql
    SQL_SERVER_HOST: sqlserver

services:
  pypy:
    build:
      context: .
      args:
        BASE_IMAGE: pypy:3.9-7.3.16-bookworm
    <<: *common-setup

  cpython:
    build:
      context: .
      args:
        BASE_IMAGE: python:3.9-bookworm
    <<: *common-setup

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-password
      MYSQL_USER: sa
      MYSQL_PASSWORD: Password123

  postgresql:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password123

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
